### ISSUE TITLE
Layers/masks not public docs?

### ISSUE THREAD

**Issue by MSGhero** [AustinEast/echo#23]
Hey, I'm wondering why `body.layers` and `layer_mask` are hidden by default and then not directly used in `world.listen()`. It doesn't have to copy Nape or anything, but I'm trying to see if maintaining arrays of bodies is the intended approach. For instance:

```haxe

/// constructor

players = [];
enemies = [];
pAttacks = [];
eAttacks = [];
platforms = [];

/// listener setup

world.listen(players, platforms, playerPlatformParams);
// etc for every pair of interacting arrays with unique callbacks

/// on new body, with custom type field

if (body.type == E_ATTACK) eAttacks.push(body);
// etc for every type
```

Even still, I currently plan to use layers to not interact in some cases where the listener `condition` would get a bit ugly.

**Comment by AustinEast** [comment]
They're hidden due to me not having a moment to fully test them (I personally haven't used them in a game yet hehe), but they are technically implemented and usable! (see this method - https://github.com/AustinEast/echo/blob/master/echo/Collisions.hx#L217)

And yes, maintaining arrays of bodies is probably the simplest approach, but I've also used a single listener and extra data to help filter collision responses, etc. its intentionally left un-opinionated, so its really up to how you'd like to tackle it in your project.

**Comment by MSGhero** [comment]
Ok thanks for the info. It may be worth it for me to add a few more things to `Body` then
